spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    data: classpath:data.sql
jenkins:
  url: http://localhost:8090/
  id: admin
  password: 111f408e7a67229deb70e1485d13c21f15
message:
  locale: KR
  encoding: UTF-8