server:
  servlet:
    context-path: /jindev
spring:
  data:
    rest:
      defaultPageSize: 10
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    data: classpath:data.sql
jenkins:
  url: http://10.20.200.201:32080/
  id: admin
  password: Rsx7vBJxu7
#  password: 111f408e7a67229deb70e1485d13c21f15
message:
  locale: KR
  encoding: UTF-8